# --- START OF CORRECTED FILE Pro_Rix/cloudbuild.yaml ---
# Version 1.2 - Use :latest tag instead of :$COMMIT_SHA
steps:
  # Step 0: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        # Tag the image with :latest
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pro-rix/${_SERVICE_NAME}:latest', 
        '-f', 'cloud_services/${_SERVICE_NAME}/Dockerfile', 
        '.' 
        ]
    id: 'Build Image'

  # Step 1: Push the built image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    # Push the :latest tag
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pro-rix/${_SERVICE_NAME}:latest']
    id: 'Push Image'
    
  # Step 2: Deploy the pushed image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run', 'deploy', '${_SERVICE_NAME}', 
        # Deploy the :latest image
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pro-rix/${_SERVICE_NAME}:latest',
        '--platform', 'managed',
        '--region', 'us-central1', 
        '--allow-unauthenticated',
        '--service-account', '613283569085-compute@developer.gserviceaccount.com',
        '--project', '$PROJECT_ID'
        ]
    id: 'Deploy to Cloud Run'

substitutions:
  _SERVICE_NAME: 'rix-manager-service' 

# Specify the :latest image tag
images: ['us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pro-rix/${_SERVICE_NAME}:latest']

# timeout: '1200s' 
# --- END OF CORRECTED FILE Pro_Rix/cloudbuild.yaml ---